# Generated by Django 2.1.1 on 2018-09-01 14:59

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180901_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='category', chained_model_field='category', default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Subcategory'),
        ),
    ]
