# Generated by Django 2.1.1 on 2018-09-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180902_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subcategory',
        ),
    ]
